_target_: deckard.base.files.FileConfig
reports: reports
data_dir: data
directory: ${dataset}
score_dict_file: score_dict.json
params_file : params.yaml
predictions_file : predictions.json
name : default
