stages:
  prepare:
    cmd: 
      - python prepare.py -f rinex-obs -d rinex-obs
    deps: 
      - configs/prepare.yml
    outs: 
      - rinex-obs/data/data.pkl
  train:
    cmd: python train.py -f rinex-obs 
    deps:
    - configs/model.yml
    - train.py
    - rinex-obs/data/data.pkl
    outs:
    - rinex-obs/best_train/model.pkl
    - rinex-obs/best_train/data.pkl
    metrics:
    - rinex-obs/best_train/results.json:
        cache: true
    - rinex-obs/best_train/results.json
  preprocess:
    cmd: python preprocess.py -f rinex-obs 
    deps:
    - configs/preprocess.yml
    - preprocess.py
    - rinex-obs/best_train/model.pkl
    - rinex-obs/best_train/data.pkl
    outs:
    - rinex-obs/best_preprocess/data.pkl
    - rinex-obs/best_preprocess/model.pkl
    metrics:
    - rinex-obs/best_preprocess/results.json:
        cache: true
  featurize:
    cmd: python featurize.py -f rinex-obs 
    deps:
    - configs/featurize.yml
    - featurize.py
    - rinex-obs/best_preprocess/data.pkl
    - rinex-obs/best_preprocess/model.pkl
    outs:
    - rinex-obs/best_features/data.pkl
    - rinex-obs/best_features/model.pkl
    metrics:
    - rinex-obs/best_features/results.json:
        cache: true
  retrain:
    cmd: python retrain.py -f rinex-obs 
    deps:
    - rinex-obs/best_features/data.pkl
    - rinex-obs/best_features/model.pkl
    - retrain.py
    outs:
    - rinex-obs/best_retrain/model.pkl
    - rinex-obs/best_retrain/data.pkl

