stages:
  prepare:
    cmd: 
      - python layers/prepare.py
    deps: 
      - configs/prepare.yml
    outs: 
      - data/data/data.pkl
  train:
    cmd: python layers/train.py
    deps:
    - configs/model.yml
    - layers/train.py
    - data/data/data.pkl
    outs:
    - data/best_train/model.pkl
    - data/best_train/data.pkl
    metrics:
    - data/best_train/results.json:
        cache: true
  preprocess:
    cmd: python layers/preprocess.py
    deps:
    - configs/preprocess.yml
    - layers/preprocess.py
    - data/best_train/model.pkl
    - data/best_train/data.pkl
    outs:
    - data/best_preprocess/data.pkl
    - data/best_preprocess/model.pkl
    metrics:
    - data/best_preprocess/results.json:
        cache: true
  featurize:
    cmd: python layers/featurize.py
    deps:
    - configs/featurize.yml
    - layers/featurize.py
    - data/best_preprocess/data.pkl
    - data/best_preprocess/model.pkl
    outs:
    - data/best_features/data.pkl
    - data/best_features/model.pkl
    metrics:
    - data/best_features/results.json:
        cache: true
  retrain:
    cmd: python layers/retrain.py
    deps:
    - data/best_features/data.pkl
    - data/best_features/model.pkl
    - layers/retrain.py
    outs:
    - data/best_retrain/model.pkl
    - data/best_retrain/data.pkl

