defaults:
    # - _target_ : deckard.base.experiment.Experiment
    - _self_
    - data: ???
    - model: ???
    - files: default
    - scorers: default
    - override hydra/sweeper : optuna
    - override hydra/sweeper/sampler : grid
    - override hydra/launcher : joblib
dataset : ???
model_name : ???
direction : 
  - maximize
optimizers: 
   - accuracy
hydra:
  run:
    dir: ${files.directory}/logs/${stage}/
  sweep:
    dir: ${files.directory}/logs/${dataset}
    subdir : ${hydra.sweeper.study_name}/${hydra.job.num}
  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${model_name}
    storage: sqlite:///${dataset}.db
    n_jobs: 32
    n_trials : 210
    params:
      model.init.k : int(1,3,5,7,9,11)
      model.init.n : int(10, 30, 50, 100, 300, 500, 1000)
    direction: ${direction}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: 32
    prefer : processes
    verbose: 1
    timeout: null
    pre_dispatch: n_jobs
    batch_size: auto
    temp_folder: /tmp/deckard
    max_nbytes: 100000
    mmap_mode: r
