stages:
  compile:
    foreach: # iterates through each stage
      - mnist
      - cifar
      - cifar100
    do:
      cmd: python -m deckard.layers.compile --report_folder /result/${item}/reports/attack/ --results_file attack.csv --results_folder ${item} --config "../conf/compile.yaml"
      deps:
       - "../conf/compile.yaml"
      outs:
      - ${item}/attack.csv
  plot:
    foreach:
       - mnist
       - cifar
       - cifar100
    do:
      cmd: python -m deckard.layers.plots --path ${item} --file ${item}/attack.csv -o plot_data.csv -c "../conf/plots.yaml" --subset train_time,predict_proba_time,accuracy,adv_accuracy,adv_fit_time
      deps:
        - ${item}/attack.csv
        - "../conf/plots.yaml"
      outs:
        - ${item}/plot_data.csv
  afr:
    foreach:
       - mnist
       - cifar
       - cifar100
    do:
      cmd: python -m deckard.layers.afr --dataset ${item} --data_file ${item}/plot_data.csv 
      deps:
        - ${item}/plot_data.csv
      plots:
        - ${item}/weibull_aft.pdf
        - ${item}/weibull_partial_effects.pdf
        - ${item}/cox_partial_effects.pdf
        - ${item}/cox_aft.pdf
        - ${item}/log_logistic_aft.pdf
        - ${item}/log_logistic_partial_effects.pdf
        - ${item}/log_normal_aft.pdf
        - ${item}/log_normal_partial_effects.pdf
      metrics:
        - ${item}/aft_comparison.csv
      outs:
        - ${item}/aft_comparison.tex