stages:
  prepare:
    cmd: 
      - python ../../layers/prepare.py  -d 'car.csv'
    deps: 
      - configs/prepare.yml
      - ../../base/data.py
      - data/pygps.csv
    outs: 
      - data/data.pkl
  train:
    cmd: python ../../layers/train.py  -f data -s mse -b False
    deps:
    - ../../base/utils.py
    - configs/model.yml
    - ../../layers/train.py
    - ../../base/experiment.py
    - data/data.pkl
    outs:
    - data/best_train/experiment.pkl
    - data/best_train/data_params.json:
        cache: true
    - data/best_train/model_params.json:
        cache: true
    metrics:
    - data/best_train/results.json:
        cache: true
    
  preprocess:
    cmd: python ../../layers/preprocess.py  -f data -s mse -b False
    deps:
    - configs/preprocess.yml
    - ../../layers/preprocess.py
    - data/best_train/experiment.pkl
    outs:
    - data/best_preprocess/experiment.pkl
    - data/best_preprocess/data_params.json:
        cache: true
    - data/best_preprocess/model_params.json:
        cache: true
    metrics:
    - data/best_preprocess/results.json:
        cache: true
   
  featurize:
    cmd: python ../../layers/featurize.py  -f data -s mse -b False
    deps:
    - configs/featurize.yml
    - ../../layers/featurize.py
    - data/best_preprocess/experiment.pkl
    outs:
    - data/best_features/experiment.pkl
    - data/best_features/data_params.json:
        cache: true
    - data/best_features/model_params.json:
        cache: true
    metrics:
    - data/best_features/results.json:
        cache: true
  evaluate:
    cmd: python ../../layers/evaluate.py -f data -s mse -d "test_gps.csv"
    deps: 
      - data/best_features/experiment.pkl
      - ./test_gps.csv



