- name: sklearn.preprocessing.StandardScaler
  params: 
    'with_mean' : [False, True]
    'with_std' : [False, True]

- name: sklearn.impute.SimpleImputer
  params: 
    'strategy' : ['mean', 'most_frequent', 'constant']
    'fill_value' : [0]

